name: Docker Image CI

on:
  push:
    branches: [ Mall-CI ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      -
        name: Build and push front end project
        uses: docker/build-push-action@v2
        with:
          context: ./Mall-web/project
          push: true
          tags: w929732982/mall-web:latest
      - name: build goods-browse
        run: mvn clean package -f Mall-server/project/pom.xml -DskipTests=true -Dmaven.javadoc.skip=true -B -V
      - name: push goods-browse
        uses: docker/build-push-action@v2
        with:
          context: ./Mall-server/project/mall-application/goods-browse-application
          push: true
          tags: w929732982/mall-goods-browse:latest
      - name: push goods-feedback
        uses: docker/build-push-action@v2
        with:
          context: ./Mall-server/project/mall-application/goods-feedback-application
          push: true
          tags: w929732982/mall-goods-feedback:latest
      - name: push goods-statistics
        uses: docker/build-push-action@v2
        with:
          context: ./Mall-server/project/mall-application/goods-statistics-application
          push: true
          tags: w929732982/mall-goods-statistics:latest
      - name: push order-cancel
        uses: docker/build-push-action@v2
        with:
          context: ./Mall-server/project/mall-application/order-cancel-application
          push: true
          tags: w929732982/mall-order-cancel:latest
      - name: push order-create
        uses: docker/build-push-action@v2
        with:
          context: ./Mall-server/project/mall-application/order-create-application
          push: true
          tags: w929732982/mall-order-create:latest
      - name: push order-payment
        uses: docker/build-push-action@v2
        with:
          context: ./Mall-server/project/mall-application/order-payment-application
          push: true
          tags: w929732982/mall-order-payment:latest
      - name: push user-info
        uses: docker/build-push-action@v2
        with:
          context: ./Mall-server/project/mall-application/user-info-application
          push: true
          tags: w929732982/mall-user-info:latest
      - name: push user-login
        uses: docker/build-push-action@v2
        with:
          context: ./Mall-server/project/mall-application/user-login-application
          push: true
          tags: w929732982/mall-user-login:latest
      - name: push user-register
        uses: docker/build-push-action@v2
        with:
          context: ./Mall-server/project/mall-application/user-register-application
          push: true
          tags: w929732982/mall-user-register:latest
