name: Build and push to Docker

on:
  push:
    branches: [ Mall-CI ]
env:
  REGION_ID: cn-beijing
  REGISTRY: registry.cn-beijing.aliyuncs.com
  NAMESPACE: w929732982
  TAG: latest

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to ACR
        uses: aliyun/acr-login@v1
        with:
          login-server: registry.cn-beijing.aliyuncs.com
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and push image to ACR
        run: |
          docker build -t "$REGISTRY/$NAMESPACE/mall-web:$TAG" Mall-web/project
          docker push "$REGISTRY/$NAMESPACE/mall-web:$TAG"

      - name: build mall-server project
        run: mvn clean package -f Mall-server/project/pom.xml -DskipTests=true -Dmaven.javadoc.skip=true -B -V

      - name: push goods-browse
        run: |
          docker build -t "$REGISTRY/$NAMESPACE/mall-goods-browse:$TAG" Mall-web/project/mall-application/goods-browse-application
          docker push "$REGISTRY/$NAMESPACE/mall-goods-browse:$TAG"

      - name: push goods-feedback
          run: |
          docker build -t "$REGISTRY/$NAMESPACE/mall-goods-feedback:$TAG" Mall-web/project/mall-application/goods-feedback-application
          docker push "$REGISTRY/$NAMESPACE/mall-goods-feedback:$TAG"

      - name: push goods-statistics
          run: |
          docker build -t "$REGISTRY/$NAMESPACE/mall-goods-statistics:$TAG" Mall-web/project/mall-application/goods-statistics-application
          docker push "$REGISTRY/$NAMESPACE/mall-goods-statistics:$TAG"

      - name: push order-cancel
          run: |
          docker build -t "$REGISTRY/$NAMESPACE/mall-order-cancel:$TAG" Mall-web/project/mall-application/order-cancel-application
          docker push "$REGISTRY/$NAMESPACE/mall-order-cancel:$TAG"

      - name: push order-create
          run: |
          docker build -t "$REGISTRY/$NAMESPACE/mall-order-create:$TAG" Mall-web/project/mall-application/order-create-application
          docker push "$REGISTRY/$NAMESPACE/mall-order-create:$TAG"

      - name: push order-payment
          run: |
          docker build -t "$REGISTRY/$NAMESPACE/mall-order-payment:$TAG" Mall-web/project/mall-application/order-payment-application
          docker push "$REGISTRY/$NAMESPACE/mall-order-payment:$TAG"

      - name: push user-info
          run: |
          docker build -t "$REGISTRY/$NAMESPACE/mall-user-info:$TAG" Mall-web/project/mall-application/user-info-application
          docker push "$REGISTRY/$NAMESPACE/mall-user-info:$TAG"

      - name: push user-login
          run: |
          docker build -t "$REGISTRY/$NAMESPACE/mall-user-login:$TAG" Mall-web/project/mall-application/user-login-application
          docker push "$REGISTRY/$NAMESPACE/mall-user-login:$TAG"

      - name: push user-register
          run: |
          docker build -t "$REGISTRY/$NAMESPACE/mall-user-register:$TAG" Mall-web/project/mall-application/user-register-application
          docker push "$REGISTRY/$NAMESPACE/mall-user-register:$TAG"
